# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

JFROG failed task :
- task: JfrogCliV2@1
  displayName: 'Configure dotnet'
  env:
    JFROG_CLI_LOG_LEVEL: DEBUG
  inputs:
    # msbuildArgs: /p:RunWixToolsOutOfProc=true
    jfrogPlatformConnection: ${{ parameters.jfrogPlatformConnection }}
    # workingDirectory: 'c:/Program Files (x86)/WiX Toolset v3.11/bin'
    command: |
      jf dotnetc --repo-resolve=${{ parameters.remote_repository_private }}
      jf dotnet restore GatewaySetup\Gateway.sln --build-name="IConnectGW-Build" --build-number=${{ parameters.build_number }} --project ${{ parameters.projectkey }} --module=dotnet
